### ISSUE TITLE
Development environment setup

### ISSUE THREAD

**Issue by rupendra1817** [IntelLedger/sawtooth-mktplace#1] opened 2016-05-11 11:14 UTC
I want to setup development environment for develop my custom mktplace. 
I want to know given below details to setup development environment-
1- Operating system
2- IDE name
3- Dependencies if any

If any one have development environment setup guide then kindly share it.

**Comment by jsmitchell** [comment] 2016-05-11 13:48
Closing as a duplicate of https://github.com/IntelLedger/sawtooth-dev-tools/issues/3

**Closed by jsmitchell** 2016-05-11 13:48 UTC
